list =[1,2,8,4,3,6]
print("length of list",len(list))
print("first element of list",list[0])
print("last element of list",list[-1])
list.append(7)
print(list)
list.sort()
print(list)
list.remove(6)
print(list)
list.reverse()
print(list)
list.pop(5)
print(list)
list.insert(4,"z")
print(list)
print("multiplication on list", list*2)
print(list[:5])
print(list[0:])
list.clear()
print("updated list",list)